services:
  postgres:
    image: postgres:15
    container_name: taskmanager_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: taskpass
      POSTGRES_DB: taskdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task-network
volumes:
  postgres_data:

networks:
  task-network:
